# Generated by Django 5.2 on 2025-04-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudante', 'curso')},
        ),
    ]
