# Generated by Django 6.0.5 on 2026-06-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_curso_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
